supplier:
  info:
    protocol: s3
    bucketname: farmfox-stg-bucket
    path: "{0}://{1}/configs/supplierInfo.yaml"
spring:
  config:
    import: aws-parameterstore:/farmfox-${spring.profiles.active}/
farmfox:
  data:
    bestsellerpath: "farmfoxdata/bestseller.json"
    valueComboProductpath: "farmfoxdata/valueComboProducts.json"
    recommendedProductPath: "farmfoxdata/recommendedProducts.json"
    videoBannerPath: "farmfoxdata/videoBanner.json"
    collectionDetailsPath: "farmfoxdata/collectionDetails.json"
    promoVideoDetaisPath: "farmfoxdata/promoVideoDetails.json"
    brandPromiseDetaisPath: "farmfoxdata/brandPromise.json"
    blogsDetailsPath: "farmfoxdata/blogsDetails.json"
    faqsDetailsPath: "farmfoxdata/faqsDetails.json"
    seoContentDetailsPath: "farmfoxdata/seoContent.json"
    mediaTalksDetailsPath: "farmfoxdata/mediaTalks.json"
    productDetailsPath: "farmfoxdata/products.json"