supplier:
  info:
    protocol: file
    bucketname: C:/Users/Aditya Prakash
    path: "{0}:{1}/configs/supplierInfo.yaml"
farmfox:
  data:
    bestSellerPath: "C:/Users/Aditya Prakash/configs/bestseller.json"
    valueComboProductpath: "C:/Users/Aditya Prakash/configs/valueComboProducts.json"
    recommendedProductPath: "C:/Users/Aditya Prakash/configs/recommendedProducts.json"
    videoBannerPath: "C:/Users/Aditya Prakash/configs/videoBanner.json"
    collectionDetailsPath: "C:/Users/Aditya Prakash/configs/collectionDetails.json"
    promoVideoDetaisPath: "C:/Users/Aditya Prakash/configs/promoVideoDetails.json"
    brandPromiseDetaisPath: "C:/Users/Aditya Prakash/configs/brandPromise.json"
    blogsDetailsPath: "C:/Users/Aditya Prakash/configs/blogsDetails.json"
    faqsDetailsPath: "C:/Users/Aditya Prakash/configs/faqsDetails.json"
    seoContentDetailsPath: "C:/Users/Aditya Prakash/configs/seoContent.json"
    mediaTalksDetailsPath: "C:/Users/Aditya Prakash/configs/mediaTalks.json"
    productDetailsPath: "C:/Users/Aditya Prakash/configs/products.json"